<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-tw" xml:lang="zh-tw">
  <head>
    <title>Recover捕获异常 | Go语言圣经</title>
    <meta name="description" content=""/>
    <meta name="generator" content="GitBook 2.6.7"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link href="stylesheet.css" rel="stylesheet" type="text/css"/>
<link href="page_styles.css" rel="stylesheet" type="text/css"/>
</head>
  <body class="dir">
        
        
<div class="page">
    
        <h1 class="book-chapter" id="calibre_toc_48">Recover捕获异常</h1>
        
            <div class="section" id="section-">
            
                <h2 id="510-recover捕获异常" class="calibre14">5.10. Recover捕获异常</h2>
<p class="calibre6">通常来说，不应该对panic异常做任何处理，但有时，也许我们可以从异常中恢复，至少我们可以在程序崩溃前，做一些操作。举个例子，当web服务器遇到不可预料的严重问题时，在崩溃前应该将所有的连接关闭；如果不做任何处理，会使得客户端一直处于等待状态。如果web服务器还在开发阶段，服务器甚至可以将异常信息反馈到客户端，帮助调试。</p>
<p class="calibre6">如果在deferred函数中调用了内置函数recover，并且定义该defer语句的函数发生了panic异常，recover会使程序从panic中恢复，并返回panic value。导致panic异常的函数不会继续运行，但能正常返回。在未发生panic时调用recover，recover会返回nil。</p>
<p class="calibre6">让我们以语言解析器为例，说明recover的使用场景。考虑到语言解析器的复杂性，即使某个语言解析器目前工作正常，也无法肯定它没有漏洞。因此，当某个异常出现时，我们不会选择让解析器崩溃，而是会将panic异常当作普通的解析错误，并附加额外信息提醒用户报告此错误。</p>
<pre class="calibre15"><code class="pcalibre8 calibre16 pcalibre7"><span class="hljs-keyword">func</span> Parse(input <span class="hljs-typename">string</span>) (s *Syntax, err error) {
    <span class="hljs-keyword">defer</span> <span class="hljs-keyword">func</span>() {
    <span class="hljs-keyword">if</span> p := <span class="hljs-number">recover</span>(); p != <span class="hljs-number">nil</span> {
        err = fmt.Errorf(<span class="hljs-string">"internal error: %v"</span>, p)
    }
    }()
    <span class="hljs-comment">// ...parser...</span>
}
</code></pre>
<p class="calibre6">deferred函数帮助Parse从panic中恢复。在deferred函数内部，panic value被附加到错误信息中；并用err变量接收错误信息，返回给调用者。我们也可以通过调用runtime.Stack往错误信息中添加完整的堆栈调用信息。</p>
<p class="calibre6">不加区分的恢复所有的panic异常，不是可取的做法；因为在panic之后，无法保证包级变量的状态仍然和我们预期一致。比如，对数据结构的一次重要更新没有被完整完成、文件或者网络连接没有被关闭、获得的锁没有被释放。此外，如果写日志时产生的panic被不加区分的恢复，可能会导致漏洞被忽略。</p>
<p class="calibre6">虽然把对panic的处理都集中在一个包下，有助于简化对复杂和不可以预料问题的处理，但作为被广泛遵守的规范，你不应该试图去恢复其他包引起的panic。公有的API应该将函数的运行失败作为error返回，而不是panic。同样的，你也不应该恢复一个由他人开发的函数引起的panic，比如说调用者传入的回调函数，因为你无法确保这样做是安全的。</p>
<p class="calibre6">有时我们很难完全遵循规范，举个例子，net/http包中提供了一个web服务器，将收到的请求分发给用户提供的处理函数。很显然，我们不能因为某个处理函数引发的panic异常，杀掉整个进程；web服务器遇到处理函数导致的panic时会调用recover，输出堆栈信息，继续运行。这样的做法在实践中很便捷，但也会引起资源泄漏，或是因为recover操作，导致其他问题。</p>
<p class="calibre6">基于以上原因，安全的做法是有选择性的recover。换句话说，只恢复应该被恢复的panic异常，此外，这些异常所占的比例应该尽可能的低。为了标识某个panic是否应该被恢复，我们可以将panic value设置成特殊类型。在recover时对panic value进行检查，如果发现panic value是特殊类型，就将这个panic作为errror处理，如果不是，则按照正常的panic进行处理（在下面的例子中，我们会看到这种方式）。</p>
<p class="calibre6">下面的例子是title函数的变形，如果HTML页面包含多个<code class="calibre12 pcalibre5 pcalibre6">&lt;title&gt;</code>，该函数会给调用者返回一个错误（error）。在soleTitle内部处理时，如果检测到有多个<code class="calibre12 pcalibre5 pcalibre6">&lt;title&gt;</code>，会调用panic，阻止函数继续递归，并将特殊类型bailout作为panic的参数。</p>
<pre class="calibre15"><code class="pcalibre8 calibre16 pcalibre7"><span class="hljs-comment">// soleTitle returns the text of the first non-empty title element</span>
<span class="hljs-comment">// in doc, and an error if there was not exactly one.</span>
<span class="hljs-keyword">func</span> soleTitle(doc *html.Node) (title <span class="hljs-typename">string</span>, err error) {
    <span class="hljs-keyword">type</span> bailout <span class="hljs-keyword">struct</span>{}
    <span class="hljs-keyword">defer</span> <span class="hljs-keyword">func</span>() {
        <span class="hljs-keyword">switch</span> p := <span class="hljs-number">recover</span>(); p {
        <span class="hljs-keyword">case</span> <span class="hljs-number">nil</span>:
        <span class="hljs-comment">// no panic</span>
        <span class="hljs-keyword">case</span> bailout{}:
        <span class="hljs-comment">// "expected" panic</span>
            err = fmt.Errorf(<span class="hljs-string">"multiple title elements"</span>)
        <span class="hljs-keyword">default</span>:
            <span class="hljs-number">panic</span>(p) <span class="hljs-comment">// unexpected panic; carry on panicking</span>
        }
    }()
    <span class="hljs-comment">// Bail out of recursion if we find more than one nonempty title.</span>
    forEachNode(doc, <span class="hljs-keyword">func</span>(n *html.Node) {
        <span class="hljs-keyword">if</span> n.Type == html.ElementNode &amp;&amp; n.Data == <span class="hljs-string">"title"</span> &amp;&amp;
            n.FirstChild != <span class="hljs-number">nil</span> {
            <span class="hljs-keyword">if</span> title != <span class="hljs-string">""</span> {
                <span class="hljs-number">panic</span>(bailout{}) <span class="hljs-comment">// multiple titleelements</span>
            }
            title = n.FirstChild.Data
        }
    }, <span class="hljs-number">nil</span>)
    <span class="hljs-keyword">if</span> title == <span class="hljs-string">""</span> {
        <span class="hljs-keyword">return</span> <span class="hljs-string">""</span>, fmt.Errorf(<span class="hljs-string">"no title element"</span>)
    }
    <span class="hljs-keyword">return</span> title, <span class="hljs-number">nil</span>
}
</code></pre>
<p class="calibre6">在上例中，deferred函数调用recover，并检查panic value。当panic value是bailout{}类型时，deferred函数生成一个error返回给调用者。当panic value是其他non-nil值时，表示发生了未知的panic异常，deferred函数将调用panic函数并将当前的panic value作为参数传入；此时，等同于recover没有做任何操作。（请注意：在例子中，对可预期的错误采用了panic，这违反了之前的建议，我们在此只是想向读者演示这种机制。）</p>
<p class="calibre6">有些情况下，我们无法恢复。某些致命错误会导致Go在运行时终止程序，如内存不足。</p>
<p class="calibre6"><strong class="calibre19">练习5.19：</strong> 使用panic和recover编写一个不包含return语句但能返回一个非零值的函数。</p>

            
            </div>
        
    
</div>

        
        
    
    

</body></html>
